version: '3.9'
services:


  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper
    volumes:
      - ./src:/app
    command: python main.py


volumes:
  db_data: